---
title: "bluedot_api"
author: "Aldilas AN"
date: "2023-06-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE, warning=FALSE, include=FALSE}
library(httr)
library(jsonlite)
library(tidyverse)
library(flextable)
library(lubridate)
library(ggthemes)
```

# Disease Alert

<https://developer.bluedot.global/assessments/>[?diseaseIds][&locationIds][&startDate][&endDate][&concernLevel][&contextTagTypeId][&eventId][&formatWithHtml][&includeCsv]&api-version=v1

```{r}
url <- ("https://developer.bluedot.global/assessments/?startDate=2023-06&formatWithHtml=false&api-version=v1")
res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache"))
parse <- content(res)
data <- data.frame(t(sapply(parse$data,c)))
View(data)
```

# Human Disease Cases and Deaths

## By Disease for location(s)

<https://developer.bluedot.global/casecounts/diseases/%7BdiseaseId%7D>[?locationIds][&startDate][&endDate][&isAggregated][&includeSources][&includeCsv]&api-version=v1

```{r}
url <- "https://developer.bluedot.global/casecounts/diseases/55?locationIds=1820814,%201831722,%201643084,%201655842,%201733045,%201327865,%201694008,%201880251,%201605651,%201562822,%201966436&startDate=2020-01&endDate=2023-06-01&isAggregated=true&api-version=v1" 
res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache"))
parse <- content(res)
data <- data.frame(t(sapply(parse$data,c)))
View(data)
```

## By Location for disease(s)

<https://developer.bluedot.global/casecounts/locations/%7BlocationId%7D>[?diseaseIds][&startDate][&endDate][&isAggregated][&subLocationTypes][&includeSources][&includeCsv]&api-version=v1

```{r pressure, echo=FALSE}
url <- "https://developer.bluedot.global/casecounts/locations/1643084?diseaseIds=200,%2055&startDate=2023-01&endDate=2023-06&isAggregated=true&api-version=v1"
res <- GET(locationUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache"))
parse <- content(res)
data <- data.frame(t(sapply(parse$data,c)))
View(data)
```

# Population Air Travel Historical Volumes

<https://developer.bluedot.global/travel/air/>[?originLocationIds][&destinationLocationIds][&originAggregationType][&destinationAggregationType][&startDate][&endDate][&includeCsv]&api-version=v1

```{r}
flightUrl <- "https://developer.bluedot.global/travel/air/?originLocationIds=1643084&destinationLocationIds=1643084&originAggregationType=4&destinationAggregationType=4&startDate=2022-06&endDate=2022-12&api-version=v1"
res <- GET(flightUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache"))
parse <- content(res)
data <- data.frame(t(sapply(parse$data,c)))
View(data)
```

# COVID-19 Vaccination Coverage

<https://developer.bluedot.global/vulnerability-indicator/vaccination/diseases/200/>[?countryIds][&startDate][&endDate][&includeCsv]&api-version=v1

```{r}
vaccUrl <- "https://developer.bluedot.global/vulnerability-indicator/vaccination/diseases/200/?countryIds=1820814,%201831722,%201643084,%201655842,%201733045,%201327865,%201694008,%201880251,%201605651,%201562822,%201966436&endDate=2023-06-11&&api-version=v1"
res <- GET(vaccUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache"))
parse <- content(res)
data <- data.frame(t(sapply(parse$data,c)))
data_edit <- data |> group_by(countryName) |> arrange(desc(reportedDate)) |> filter(row_number()==1)
data_edit$cumulativePeopleVaccinated <- as.numeric(data_edit$cumulativePeopleVaccinated)
data_edit$vaccinatedPercentage <- (data_edit$cumulativePeopleVaccinated*270203900)*100
data$reportedDate <- ymd(substr(data$reportedDate, 1, 10))
View(data)
```

# Surface Temperature

<https://developer.bluedot.global/vulnerability-indicator/surface-temperature/>[?locationIds][&locationType][&startDate][&endDate][&includeCsv]&api-version=v1

```{r paged.print=TRUE}
url <- "https://developer.bluedot.global/vulnerability-indicator/surface-temperature/?locationIds=1820814,1831722,1643084,1655842,1733045,1327865,01694008,1880251,1605651,1562822&startDate=2017-01&api-version=v1"
res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
tempData <- enframe(pluck(res, "data")) |> unnest_wider(value)
#flextable(tempData)
```

```{r paged.print=TRUE}
df <- tempData |> 
  mutate(date = as.Date(paste0(aggregationMonth, "-01"), format = "%Y-%m-%d")) |> 
  group_by(date) |> summarise(avgTemp = mean(avgTemperature),
                              minTemp = mean(minTemperature),
                              maxTemp = mean(maxTemperature)) |> 
  pivot_longer(cols = c(avgTemp:maxTemp), names_to = "var", values_to = "temp")
df_avg <- df |> 
  mutate(qtr = quarter(date, type = "date_last"), temp = round(temp, 2)) |>
  group_by(qtr, var) |> filter(row_number()==n())
```

```{r}
plot <- ggplot(df |> filter(date >= "2021-01-01")) + 
  geom_col(aes(x = date, y = temp, fill = var)) +
  geom_smooth(data = df |> filter(var == "avgTemp", date >= "2021-01-01"),
              aes(x = date, y = as.numeric(temp)), 
              method = "lm", size = 1, color = "black")
plot
```

```{r}
plot <- ggplot(df |> filter(date >= "2022-01-01")) + 
  geom_smooth(aes(x = date, y = as.numeric(temp), color = var), 
              method = "loess", size = 1, se = FALSE) +
  geom_text(data = filter(df_avg, qtr >= "2022-01-01" && qtr <= "2023-07-01"), 
            aes(qtr, as.numeric(temp), label = temp)) +
  xlab(element_blank()) +
  ylab("Temperature (\u00B0C)")+
  scale_color_manual(name = element_blank(), 
                     values = c("green", "red", "blue"),
                     labels = c("Average Temperature", "Max Temperature", "Min Temperature")) +
  theme_hc(base_size = 16)
plot
```

```{r}
jpeg("ASEAN avg temp 2022-2023.jpeg", units="px", width=4000, height=2250, res=300)
plot
dev.off()
```
