---
title: "covid-19 data collection"
output: html_document
date: "2023-07-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(scales)
library(lubridate)
library(flextable)
library(httr)
library(jsonlite)
library(zoo)
library(highcharter)
```

# Data Import

```{r WHO data, paged.print=TRUE}
#link <- "https://covid19.who.int/WHO-COVID-19-global-data.csv"
#download.file(link, "WHO-COVID-19-global-data.csv")
who_data <- read_csv("~/Downloads/WHO-COVID-19-global-data.csv") |> 
  filter(Country_code %in% c("BN", "KH", "ID", "LA", "PH", "TH", "VN", "MM", "SG", "MY")) |> 
  mutate(Country = replace(Country, Country == "Lao People's Democratic Republic", "Lao PDR"),
         Country = replace(Country, Country == "Brunei Darussalam", "Brunei DS"),
         Country = replace(Country, Country == "Viet Nam", "Vietnam"))
#tail(data)
#View(data)
```

```{r OWID data, paged.print=TRUE}
link <- "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
download.file(link, "owid-covid-data.csv")
owid_data <- read_csv("owid-covid-data.csv") |> 
  filter(iso_code %in% c("BRN", "KHM", "IDN", "LAO", "PHL", "THA", "VNM", "MMR", "SGP", "MYS")) |> 
  mutate(location = replace(location, location == "Laos", "Lao PDR"),
         location = replace(location, location == "Brunei", "Brunei DS"))
```

```{r}
owid_data$week <- floor_date(owid_data$date, "week")
```

```{r}
replacement_data <- who_data |> filter(Country_code == "PH", Date_reported >= "2022-12-25" & Date_reported <= "2023-08-20") |> 
  select(Country_code, Date_reported, Cumulative_cases) |> mutate(Cumulative_cases = Cumulative_cases-65079,
                                                                  New_cases = c(Cumulative_cases[1], diff(Cumulative_cases))) |> 
  slice(2:(n() - 1))
```

```{r}
replaced_who_data <- merge(who_data, replacement_data, by = c("Country_code", "Date_reported", "Cumulative_cases"))
```

# Recent updates
```{r}
last_data <- df_who |> group_by(Country) |> filter(row_number()==n())
```


# Graph

```{r weekly plot 2023 ggplot2}
plot <- ggplot() +
  geom_area(data = who_data, aes(x = Date_reported, y = New_cases, fill = Country)) + 
  geom_line(data = who_data, aes(Date_reported, New_deaths*100, colour = "Number of Death"), linetype = "solid", linewidth = 1.2) +
  scale_y_continuous(sec.axis = sec_axis(~ . / 200, name = "No. of Death"), name = "Weekly Cases") +
  scale_x_date(breaks = "1 month", labels = date_format("%b-%Y"),
               limits = as.Date(c('2022-12-25','2023-12-16')), name = element_blank()) +
  scale_colour_manual("", breaks = c("Number of Death"), values = "black") +
  theme(legend.title = element_blank()) +
  theme_hc()
plot
```

```{r weekly plot 2023 ggplot2 from OWID data}
owid_weekly_data <- owid_data |> filter(date >= "2023-01-01") |> group_by(location, week) |> 
  summarise(cases = sum(new_cases, na.rm = TRUE), deaths = sum(new_deaths, na.rm = TRUE)) |> ungroup()
owid_weekly_deaths <- owid_weekly_data |> group_by(week) |> summarise(deaths = sum(deaths)) |> ungroup()
plot <- ggplot() +
  geom_area(data = owid_weekly_data, aes(x = week, y = cases, fill = location)) + 
  geom_line(data = owid_weekly_deaths, aes(week, deaths*200, colour = "Number of Death"), linetype = "solid", linewidth = 1.2) +
  scale_y_continuous(sec.axis = sec_axis(~ . / 200, name = "No. of Death"), name = "Weekly Cases") +
  scale_x_date(breaks = "1 month", labels = date_format("%b-%Y"),
               limits = as.Date(c('2022-12-25','2023-12-31')), name = element_blank()) +
  scale_colour_manual("", breaks = c("Number of Death"), values = "black") +
  theme(legend.title = element_blank()) +
  theme_hc()
plot
```

```{r weekly plot 6 mo}
plot <- ggplot() +
  geom_area(data = weeklyData, aes(x = date, y = weekly_cases, fill = Country)) + 
  geom_line(data = weeklyDeath, aes(date, weekly_deaths*100, colour = "Number of Death"), linetype = "solid", linewidth = 1.2) +
  scale_y_continuous(sec.axis = sec_axis(~ . / 100, name = "No. of Death"), name = "Weekly Cases") +
  scale_x_date(breaks = "1 month", labels = date_format("%b-%Y"),
               limits = as.Date(c('2023-07-01','2023-12-24')), name = element_blank()) +
  scale_colour_manual("", breaks = c("Number of Death"), values = "black") +
  theme(legend.title = element_blank()) +
  theme_hc() + ylim(0, 25000)
plot
```

```{r export}
png("weekly curve COVID-19 ASEAN 26 December 2023 area.png", units="px", width=3000, height=2250, res=300)
plot
dev.off()
```

```{r weekly plot 2023 highcharter}
# df_who <- who_data |> filter(Date_reported >= "2023-01-01")
# df_who$New_cases[df_who$Date_reported == "2023-08-20" & df_who$Country_code == "PH"] <- 0
# df_who_death <- df_who |> group_by(Date_reported) |> summarise(deaths = sum(New_deaths))
plot <- highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "No. of Cases")),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "No. of Deaths"))) |> 
  hc_add_series(data = owid_weekly_data, type = "area", hcaes(x = week, y = cases, group = location)) |> 
  hc_add_series(data = owid_weekly_deaths, type = "line", hcaes(x = week, y = deaths), yAxis = 1, name = "No. of Deaths", color = "black") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime") |> 
  hc_plotOptions(series = list(marker = list(enabled = FALSE), stacking = "normal"))
plot
```

```{r export hchart object}
htmlwidgets::saveWidget(widget = plot, file = "plot.html")
webshot::webshot(url = "plot.html", file = "plot.png", delay = 3) |> webshot::resize("4000x2250")
```


# COVID-19 vaccine data

```{r who data}
#link <- "https://covid19.who.int/who-data/vaccination-data.csv"
#download.file(link, "vaccination-data.csv")
vacc <- read_csv("~/Downloads/vaccination-data.csv") |> 
  filter(ISO3 %in% c("BRN", "KHM", "IDN", "LAO", "PHL", "THA", "VNM", "MMR", "SGP", "MYS")) |>  # nolint # nolint: line_length_linter.
  mutate(COUNTRY = replace(COUNTRY, COUNTRY == "Lao People's Democratic Republic", "Lao PDR"),
         COUNTRY = replace(COUNTRY, COUNTRY == "Viet Nam", "Vietnam")) |> 
  select(1, 5, 7, 9, 10, 11, 15, 16) |> arrange(COUNTRY)
flextable(vacc)
```

```{r owid}
vacc_data <- owid_data |> filter(iso_code %in% c("BRN", "KHM", "IDN", "LAO", "PHL", "THA", "VNM", "MMR", "SGP", "MYS"),
                                 date >= "2023-01-01") |> 
  select(iso_code, location, date, total_vaccinations:new_people_vaccinated_smoothed_per_hundred)
```

```{r}
data |> group_by(location) |> filter(row_number()==1)
```

# Indicator-based Surveillance from Bluedot 

```{r}
startDate <- "2023-10-01"
endDate <- "2023-10-21"
covUrl <- paste0("https://developer.bluedot.global/casecounts/indicator-based/?diseaseIds=200&locationIds=1880251,%201605651,%201694008,%201820814,%201733045,%201643084,%201831722,%201327865,%201655842,1562822&startDate=", startDate, "&endDate=", endDate, "&api-version=v1")
res <- GET(covUrl, add_headers("Ocp-Apim-Subscription-Key" = "371e207132a2497f8e981a8d3264788b", "Cache-Control" = "no-cache")) |> content()
covData <- enframe(pluck(res, "data")) |> unnest_wider(value)
View(covData)
flextable(covData)
```

# COVID-19 from OWID

```{r}
link <- "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/latest/owid-covid-latest.csv"
download.file(link, "owid-covid-latest.csv")
owid_data <- read_csv("owid-covid-latest.csv") |> filter(iso_code %in% c("BRN", "KHM", "IDN", "LAO", "PHL", "THA", "VNM", "MMR", "SGP", "MYS"))
View(data)
```

# COVID-19 News
```{r}
url <- "https://developer.bluedot.global/casecounts/diseases/200?locationIds=1880251,%201605651,%201694008,%201820814,%201733045,%201643084,%201831722,%201327865,%201655842,1562822&startDate=2023-10-13&endDate=2023-10-19&isAggregated=false&includeSources=true&api-version=v1"
res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
length_df <- length(res$data)
covNews <- data.frame()
for(i in 1:length_df){
  disease_name <- pluck(res, "data", i, "diseaseName")
  vec <- enframe(pluck(res, "data", i, "sources")) |> unnest_wider(value)
  vec$name <- disease_name
  covNews <- rbind(covNews, vec)
}
flextable(covNews)
```

