---
title: "COVID-19 In-depth Analysis"
author: "Aldilas AN"
date: "2023-12-21"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(ggpubr)
library(highcharter)
library(webshot2)
library(zoo)
library(ggprism)
library(jsonlite)
```

# Dataset
```{r data OWID}
# owid_url <- "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
# download.file(owid_url, "owid-covid-data.csv")
data_owid <- read_csv("owid-covid-data.csv")
```

```{r Data WHO}
# link <- "https://covid19.who.int/WHO-COVID-19-global-data.csv"
# download.file(link, "WHO-COVID-19-global-data.csv")
data_who <- read_csv("WHO-COVID-19-global-data.csv") |> 
  filter(Country_code %in% c("BN", "KH", "ID", "LA", "PH", "TH", "VN", "MM", "SG", "MY")) |> 
  mutate(Country = replace(Country, Country == "Lao People's Democratic Republic", "Lao PDR"),
         Country = replace(Country, Country == "Brunei Darussalam", "Brunei DS"),
         Country = replace(Country, Country == "Viet Nam", "Vietnam"))
```

```{r gisaid}
js <- read_json("gisaid_variants_statistics.json")
data_gisaid_variant <- pluck(js, "stats") |> 
  enframe() |> 
  unnest_longer(value) |> 
  unnest_wider(value) |> 
  select(name, value_id, submissions_per_variant) |> 
  unnest_longer(submissions_per_variant) |> 
  hoist(submissions_per_variant, variant = list(2), count = list(1)) |> 
  rename(country = value_id, date = name) |> select(-submissions_per_variant) |> 
  arrange(date)

data_gisaid_lineage <- pluck(js, "stats") |> 
  enframe() |> 
  unnest_longer(value) |> 
  unnest_wider(value) |> 
  select(name, value_id, submissions_per_lineage) |> 
  unnest_longer(submissions_per_lineage) |> 
  hoist(submissions_per_lineage, lineage = list(2), count = list(1)) |> 
  rename(country = value_id, date = name) |> select(-submissions_per_lineage) |> 
  arrange(date)

data_gisaid_lineage$line <- if_else(grepl("XBB.1.16", data_gisaid_lineage$lineage), "XBB.1.16+XBB.1.16.*",
                     if_else(grepl("XBB.1.5", data_gisaid_lineage$lineage), "XBB.1.5+XBB.1.5.*",
                             if_else(grepl("BA.2.75", data_gisaid_lineage$lineage), "BA.2.75+BA.2.75.*",
                                     if_else(grepl("CH.1.1", data_gisaid_lineage$lineage), "CH.1.1+CH.1.1.*",
                                             if_else(grepl("EG.5", data_gisaid_lineage$lineage), "EG.5+EG.5.*",
                                                     if_else(grepl("XBB.1.9.1", data_gisaid_lineage$lineage), "XBB.1.9.1+XBB.1.9.1.*",
                                                             if_else(grepl("XBB.2.3", data_gisaid_lineage$lineage), "XBB.2.3+XBB.2.3.*",
                                                                     if_else(grepl("BA.2.86", data_gisaid_lineage$lineage), "BA.2.86.*",
                                                                             if_else(grepl("B.1.640", data_gisaid_lineage$lineage), "B.1.640+B.1.640.*",
                                                                                     if_else(grepl("B.1.617.2|AY", data_gisaid_lineage$lineage), "B.1.617.2+AY*",
                                                                                             if_else(grepl("B.1.1.529|BA", data_gisaid_lineage$lineage), "Omicron B.1.1.529+BA.*",
                                                                                                     if_else(grepl("JN.1", data_gisaid_lineage$lineage), "JN.1+JN.1.*",
                                                                                                             if_else(grepl("XBB.1.9.2", data_gisaid_lineage$lineage), "XBB.1.9.2+XBB.1.9.2.*",
                                                                                                                     if_else(grepl("XBB", data_gisaid_lineage$lineage), "XBB", data_gisaid_lineage$lineage)
                                                                                                             )
                                                                                                     )
                                                                                             )
                                                                                     )
                                                                             )
                                                                     )
                                                             )
                                                     )
                                             )
                                     )
                             )
                     )
)
```

# ASEAN Region
```{r variant bar}
asean_countries <- c("Brunei", "Cambodia", "Indonesia", "Laos", "Malaysia", "Myanmar", "Philippines", "Singapore", "Thailand", "Vietnam")
asean_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country %in% asean_countries) |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, variant) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n))
ggplot(asean_variant, aes(month, pct, fill = variant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom") + xlab(element_blank()) +
  ylab("Submission Rate (%)")
```
```{r lineage bar}
asean_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country %in% asean_countries) |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n))
asean_lineage_plot <- ggplot(asean_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom") + xlab(element_blank()) +
  ylab("Submission Rate (%)") + ggtitle("Trend of COVID-19 Variants in ASEAN Region as of December 2023")
asean_lineage_plot
```

```{r lineage area}
asean_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country %in% asean_countries) |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
asean_lineage_plot <- ggplot(asean_lineage, aes(month, pct, fill = line)) +
  geom_area() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b-%y") +
  theme_prism() + theme(legend.position = "bottom") + xlab(element_blank()) +
  ylab("Submission Rate (%)") + ggtitle("Trend of COVID-19 Variants in ASEAN Region as of December 2023")
asean_lineage_plot
```

```{r export as jpeg}
jpeg("asean variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
asean_lineage_plot
dev.off()
```
# Brunei
```{r total Case and death}
data_brn <- data_owid |> filter(iso_code == "BRN", date >= "2023-01-01") |> 
  mutate(date = as.Date(date, "%Y-%m-%d"))
brn <- highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Total Cases"), color = "red"),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Total Deaths"), max = 200)) |> 
  hc_add_series(data = data_brn, type = "line", hcaes(x = date, y = total_cases), name = "Total Cases") |> 
  hc_add_series(data = data_brn, type = "line", hcaes(x = date, y = total_deaths), yAxis = 1, name = "Total Deaths") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
brn
```

```{r daily Case and death}
data_brn <- data_owid |> filter(iso_code == "BRN", date >= "2023-01-01") |> 
  mutate(new_cases_ma = rollmean(new_cases, 7, na.pad = TRUE), new_deaths_ma = rollmean(new_deaths, 7, na.pad = TRUE))
brn <- highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Daily Cases")),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Daily Deaths"))) |> 
  hc_add_series(data = data_brn, type = "spline", hcaes(x = date, y = new_cases_ma), name = "Total Cases") |> 
  hc_add_series(data = data_brn, type = "spline", hcaes(x = date, y = new_deaths_ma), yAxis = 1, name = "Total Deaths") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
brn
```

```{r variant}
brn_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Brunei") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, variant) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
ggplot(brn_variant, aes(month, pct, fill = variant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom") + ylab("Submission Rate (%)") +
  xlab(element_blank()) + ggtitle("Brunei Darussalam")
```

```{r lineage}
brn_variant_march_may <- filter(brn_variant, month > "2023-02-01" & month < "2023-06-01") |> 
  mutate(line = gsub(".*\\((.*)\\).*", "\\1", variant)) |> select(-variant)
brn_variant_march_may$line[brn_variant_march_may$line == "B.1.1.529+BA.*"] <- "Omicron B.1.1.529+BA.*"
brn_variant_march_may$line[brn_variant_march_may$line == "XBB+XBB.* excluding XBB.1.5, XBB.1.16, XBB.1.9.1, XBB.1.9.2, XBB.2.3"] <- "XBB"
brn_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Brunei") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> arrange(date) |> group_by(month, line) |> 
  summarise(n = sum(count)) |> mutate(pct = n / sum(n)*100) |> 
  full_join(brn_variant_march_may) |> arrange(month)
brn_lineage_plot <- ggplot(brn_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ylab("Submission Rate (%)") +
  xlab(element_blank()) + ggtitle("Brunei Darussalam")
brn_lineage_plot
```

```{r export as jpeg}
htmlwidgets::saveWidget(widget = brn, file = "brn.html")
getwd()
webshot(url = "brn.html", 
        file = "brn.jpeg",
        delay=3) # delay will ensure that the whole plot appears in the image
if(dev.cur() > 1) dev.off()
```

```{r export as jpeg}
jpeg("Brunei Darussalam variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
brn_lineage_plot
dev.off()
```
# Cambodia
```{r case and death}
data_khm <- data_owid |> filter(iso_code == "KHM", date >= "2023-01-01")
khm <- highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Total Cases")),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Total Deaths"))) |> 
  hc_add_series(data = data_khm, type = "line", hcaes(x = date, y = total_cases), name = "Total Cases") |> 
  hc_add_series(data = data_khm, type = "line", hcaes(x = date, y = total_deaths), yAxis = 1, name = "Total Deaths") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
khm
```

```{r variant}
khm_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Cambodia") |> 
  mutate(month = floor_date(as.Date(date), 'month'),
         line = gsub(".*\\((.*)\\).*", "\\1", variant)) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
khm_variant$line[khm_variant$line == "B.1.1.529+BA.*"] <- "Omicron B.1.1.529+BA.*"
khm_variant$line[khm_variant$line == "XBB+XBB.* excluding XBB.1.5, XBB.1.16, XBB.1.9.1, XBB.1.9.2, XBB.2.3"] <- "XBB"
khm_variant_plot <- ggplot(khm_variant, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ylab("Submission Rate (%)") +
  xlab(element_blank()) + ggtitle("Cambodia")
khm_variant_plot
```

```{r lineage}
khm_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Cambodia") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n))
ggplot(khm_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom")
```

```{r export as jpeg}
htmlwidgets::saveWidget(widget = khm, file = "khm.html")
getwd()
webshot(url = "khm.html", 
        file = "khm.jpeg",
        delay=3) # delay will ensure that the whole plot appears in the image
if(dev.cur() > 1) dev.off()
```

```{r export as jpeg}
jpeg("Cambodia variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
khm_variant_plot
dev.off()
```

# Indonesia
```{r total case and death}
data_idn <- data_owid |> filter(iso_code == "IDN", date >= "2023-01-01")
idn <- highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Total Cases")),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Total Deaths"), max = 163000)) |> 
  hc_add_series(data = data_idn, type = "line", hcaes(x = date, y = total_cases), name = "Total Cases") |> 
  hc_add_series(data = data_idn, type = "line", hcaes(x = date, y = total_deaths), yAxis = 1, name = "Total Deaths") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
idn
```

```{r daily case and death}
data_idn <- data_owid |> filter(iso_code == "IDN", date >= "2023-01-01") |> 
  mutate(new_cases_ma = rollmean(new_cases, 7, na.pad = TRUE), new_deaths_ma = rollmean(new_deaths, 7, na.pad = TRUE))
idn <- highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Daily Cases")),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Daily Deaths"), max = 50)) |> 
  hc_add_series(data = data_idn, type = "line", hcaes(x = date, y = new_cases_ma), name = "Total Cases") |> 
  hc_add_series(data = data_idn, type = "line", hcaes(x = date, y = new_deaths_ma), yAxis = 1, name = "Total Deaths") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
idn
```

```{r variant}
idn_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Indonesia") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, variant) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
ggplot(idn_variant, aes(month, pct, fill = variant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom")
```

```{r lineage}
idn_variant_may_aug <- filter(idn_variant, month > "2023-05-01" & month < "2023-09-01") |> 
  mutate(line = gsub(".*\\((.*)\\).*", "\\1", variant)) |> select(-variant)
idn_variant_may_aug$line[idn_variant_may_aug$line == "B.1.1.529+BA.*"] <- "Omicron B.1.1.529+BA.*"
idn_variant_may_aug$line[idn_variant_may_aug$line == "XBB+XBB.* excluding XBB.1.5, XBB.1.16, XBB.1.9.1, XBB.1.9.2, XBB.2.3"] <- "XBB"
idn_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Indonesia") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> arrange(date) |> group_by(month, line) |> summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100) |> full_join(idn_variant_may_aug) |> arrange(month)
idn_lineage_plot <- ggplot(idn_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ggtitle("Indonesia") + 
  ylab("Submission Rate (%)") + xlab(element_blank())
idn_lineage_plot
```
```{r hospitalised}
data_idn_hosp <- readxl::read_xlsx("data hospitalisasi covid indonesia 2023.xlsx")
idn_lineage <- idn_lineage |> filter(month >= "2023-11-01")
#ggplot(data_idn_hosp, aes(date, count)) + geom_line()
idn_hosp_lineage <- highchart() |> 
  hc_add_series(data = data_idn_hosp, type = "line", hcaes(x = as.Date(date), y = count),
                name = "Hospitalised") |>
  hc_add_yAxis(nid = 1L, title = list(text = "Number of patients"), relative = 3) |>
  hc_add_series(data = idn_lineage, type = "column", hcaes(x = month, y = pct, group = line), 
                stacking = "normal", pointWidth = 50, yAxis = 1) |> 
  hc_add_yAxis(nid = 2L, title = list(text = "Submission Rate (%)"), 
               labels = list(format = "{value}%"), max = 100, opposite = TRUE, relative = 1,
               height = "50%") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
idn_hosp_lineage
```

```{r export as jpeg}
htmlwidgets::saveWidget(widget = idn_hosp_lineage, file = "idn_hosp_lineage.html")
getwd()
webshot(url = "idn_hosp_lineage.html", 
        file = "idn_hosp_lineage.jpeg",
        delay=5) # delay will ensure that the whole plot appears in the image
if(dev.cur() > 1) dev.off()
```

```{r export as jpeg}
jpeg("Indonesia variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
idn_lineage_plot
dev.off()
```

# Lao PDR
```{r cases and death}
data_lao <- data_owid |> filter(iso_code == "LAO", date >= "2023-01-01")
highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Total Cases", opposite = FALSE)),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Total Deaths"))) |> 
  hc_add_series(data = data_lao, type = "line", hcaes(x = date, y = total_cases), name = "Total Cases") |> 
  hc_add_series(data = data_lao, type = "line", hcaes(x = date, y = total_deaths), yAxis = 1, name = "Total Deaths")
```

```{r variant}
lao_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Laos") |> 
  mutate(month = floor_date(as.Date(date), 'month'),
         line = gsub(".*\\((.*)\\).*", "\\1", variant)) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
lao_variant$line[lao_variant$line == "B.1.1.529+BA.*"] <- "Omicron B.1.1.529+BA.*"
lao_variant$line[lao_variant$line == "XBB+XBB.* excluding XBB.1.5, XBB.1.16, XBB.1.9.1, XBB.1.9.2, XBB.2.3"] <- "XBB"
lao_variant_plot <- ggplot(lao_variant, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ggtitle("Lao PDR") +
  ylab("Submission Rate (%)") + xlab(element_blank())
lao_variant_plot
```

```{r lineage}
lao_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Laos") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n))
ggplot(lao_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom") + ggtitle("Lao PDR") +
  ylab("Submission Rate (%)") + xlab(element_blank())
```

```{r export as jpeg}
jpeg("Lao PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
lao_variant_plot
dev.off()
```

# Malaysia
```{r transform data from OWID}
data_my_hosp <- data_owid |> 
  filter(iso_code == "MYS") |>
  select(iso_code:date, icu_patients, icu_patients_per_million, hosp_patients, hosp_patients_per_million, weekly_hosp_admissions, weekly_hosp_admissions_per_million) |> 
  pivot_longer(cols = icu_patients:weekly_hosp_admissions, names_to = "variable", values_to = "value")
data_my_vacc <- data_owid |> 
  filter(iso_code == "MYS") |>
  select(iso_code:date, people_vaccinated, people_fully_vaccinated, total_boosters, people_vaccinated_per_hundred,
         people_fully_vaccinated_per_hundred, total_boosters_per_hundred) |> 
  pivot_longer(cols = people_vaccinated:total_boosters_per_hundred, names_to = "variable", values_to = "value")
```

```{r plot hospitalised and icu using ggplot2}
mys_hosp <- ggplot(filter(data_my_hosp, variable %in% c("hosp_patients", "icu_patients"), date >= "2023-01-01"), aes(date, value)) + 
  geom_line(aes(color = variable)) +
  geom_line(data = filter(data_my_vacc, variable == "people_fully_vaccinated_per_hundred", date >= "2023-01-01"), aes(date, value*10)) +
  scale_x_date(date_labels = "%B", breaks = seq(ymd("2023-01-01"), ymd("2023-12-01"), by = 'month')) +
  scale_y_continuous(sec.axis = sec_axis(~ . / 10, name = "Fully vaccinated per hundred population"), name = "Daily hospitalisations") +
  theme_prism() + xlab(element_blank())
mys_hosp
```

```{r cases and deaths}
data_my <- data_owid |> filter(iso_code == "MYS", date >= "2023-01-01")
highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Total Cases", opposite = FALSE)),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Total Deaths"))) |> 
  hc_add_series(data = data_my, type = "line", hcaes(x = date, y = total_cases), name = "Total Cases") |> 
  hc_add_series(data = data_my, type = "line", hcaes(x = date, y = total_deaths), yAxis = 1, name = "Total Deaths")
```

```{r variant}
mys_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Malaysia") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, variant) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
ggplot(mys_variant, aes(month, pct, fill = variant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom")
```
```{r lineage}
mys_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Malaysia") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
mys_lineage_plot <- ggplot(mys_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") +
  ylab("Submission Rate (%)") + xlab(element_blank())
mys_lineage_plot
```
```{r join between hospitalised and variant data using hchart}
data_my_hosp <- data_my_hosp |> 
  filter(variable %in% c("hosp_patients", "icu_patients"),
                                       date >= "2023-01-01")
data_my_vacc <- data_my_vacc |> 
  filter(variable == "people_fully_vaccinated_per_hundred", date >= "2023-01-01")

mys_hosp_lineage <- highchart() |> 
  hc_add_series(data = data_my_hosp, type = "line", hcaes(x = date, y = value, group = variable),
                color = c("black", "red"), name = c("Hospitalised", "ICU")) |>
  hc_add_yAxis(nid = 1L, title = list(text = "Number of patients"), relative = 3) |>
  hc_add_series(data = mys_lineage, type = "column", hcaes(x = month, y = pct, group = line), 
                stacking = "normal", pointWidth = 20, yAxis = 1) |> 
  hc_add_yAxis(nid = 2L, title = list(text = "Submission Rate (%)"), 
               labels = list(format = "{value}%"), max = 100, opposite = TRUE, relative = 1,
               height = "50%") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
mys_hosp_lineage
```

```{r export as jpeg for ggplot2 object}
jpeg("Malaysia PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
mys_lineage_plot
dev.off()
```
```{r export as jpeg for hchart object}
htmlwidgets::saveWidget(widget = mys_hosp_lineage, file = "mys_hosp_lineage.html")
getwd()
webshot(url = "mys_hosp_lineage.html", 
        file = "mys_hosp_lineage.jpeg",
        delay=3) # delay will ensure that the whole plot appears in the image
if(dev.cur() > 1) dev.off()
```

# Myanmar
```{r variant}
mmr_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Myanmar") |> 
  mutate(month = floor_date(as.Date(date), 'month'),
         line = gsub(".*\\((.*)\\).*", "\\1", variant)) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
mmr_variant$line[mmr_variant$line == "B.1.1.529+BA.*"] <- "Omicron B.1.1.529+BA.*"
mmr_variant$line[mmr_variant$line == "XBB+XBB.* excluding XBB.1.5, XBB.1.16, XBB.1.9.1, XBB.1.9.2, XBB.2.3"] <- "XBB"
mmr_variant_plot <- ggplot(mmr_variant, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ggtitle("Myanmar") + ylab("Submission Rate (%)") +
  xlab(element_blank())
mmr_variant_plot
```

```{r export as jpeg}
jpeg("Myanmar PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
mmr_variant_plot
dev.off()
```

# Philippines
```{r case and death}
data_phl <- data_who |> filter(Country_code == "PH", Date_reported >= "2023-01-01")
highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Total Cases", opposite = FALSE)),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Total Deaths"))) |> 
  hc_add_series(data = data_phl, type = "line", hcaes(x = Date_reported, y = Cumulative_cases), name = "Total Cases") |> 
  hc_add_series(data = data_phl, type = "line", hcaes(x = Date_reported, y = Cumulative_deaths), yAxis = 1, name = "Total Deaths") |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
```

```{r variant}
phl_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Philippines") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, variant) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
ggplot(phl_variant, aes(month, pct, fill = variant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom")
```

```{r lineage}
phl_variant_july <- filter(phl_variant, month == "2023-07-01") |> 
  mutate(line = gsub(".*\\((.*)\\).*", "\\1", variant)) |> select(-variant)
phl_variant_july$line[phl_variant_july$line == "B.1.1.529+BA.*"] <- "Omicron B.1.1.529+BA.*"
phl_variant_july$line[phl_variant_july$line == "XBB+XBB.* excluding XBB.1.5, XBB.1.16, XBB.1.9.1, XBB.1.9.2, XBB.2.3"] <- "XBB"
phl_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Philippines") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100) |> 
  full_join(phl_variant_july) |> arrange(month)
phl_lineage_plot <- ggplot(phl_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ggtitle("Philippines") + ylab("Submission Rate (%)") +
  xlab(element_blank())
phl_lineage_plot
```

```{r export as jpeg}
jpeg("Philippines PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
phl_lineage_plot
dev.off()
```

# Singapore
```{r hospitalization and vaccination data from https://data.gov.sg}
data_sg_vacc <- read_csv("ProgressofCOVID19vaccination.csv") |> 
  mutate(epi_week = epiweek(vacc_date), 
         epi_year = year(vacc_date)) |> 
  filter(epi_year == 2023)
date_week <- data_sg_vacc |> group_by(epi_year, epi_week) |> filter(row_number()==n()) |> select(epi_year, epi_week, vacc_date) |> ungroup()
data_sg_hosp <- read_csv("NumberofnewCOVID19hospitalisationsICUadmissionsbyEpiweek.csv") |> 
  left_join(date_week, by = c("epi_year", "epi_week"))
```

```{r hospitalization and vaccination coverage plot}
ratio <- max(data_sg_vacc$full_regimen_pcttakeup) / min(data_sg_vacc$full_regimen_pcttakeup)
data_sg_vacc <- transform(data_sg_vacc, full_regimen_pcttakeup_scaled = full_regimen_pcttakeup * ratio)
ggplot(data_sg, aes(vacc_date, count)) + 
  geom_line(aes(color = new_admisison_type)) +
  geom_line(data = data_sg_vacc, aes(vacc_date, minimum_protection_pcttakeup*10)) +
  scale_y_continuous(sec.axis = sec_axis(~ . / 1000, name = "Population with first booster (%)",
                                         labels = scales::label_percent(), breaks = c(0.1, 0.3, 0.6, 0.8, 1)), 
                     name = "Daily hospitalisations") +
  theme_bw()
```

```{r case and death from owid}
data_sg <- data_owid |> filter(iso_code == "SGP", date >= "2023-01-01")
highchart() |> 
  hc_yAxis_multiples(
    list(title = list(text = "Total Cases", opposite = FALSE)),
    list(showLastLabel = FALSE, opposite = TRUE, title = list(text = "Total Deaths"))) |> 
  hc_add_series(data = data_sg, type = "line", hcaes(x = date, y = total_cases), name = "Total Cases") |> 
  hc_add_series(data = data_sg, type = "line", hcaes(x = date, y = total_deaths), yAxis = 1, name = "Total Deaths")
```

```{r variant}
sgp_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Singapore") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, variant) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n))
ggplot(sgp_variant, aes(month, pct, fill = variant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom")
```

```{r lineage}
sgp_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Singapore") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
sgp_lineage_plot <- ggplot(sgp_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ylab("Submisison Rate (%)") +
  xlab(element_blank()) + ggtitle("Singapore")
sgp_lineage_plot
```

```{r join between hospitalised and variant data using hchart}
data_sg_hosp <- data_sg_hosp |> 
  filter(vacc_date >= "2023-01-01")
sgp_hosp_lineage <- highchart() |> 
  hc_add_series(data = data_sg_hosp, type = "line", hcaes(x = vacc_date, y = count, group = new_admisison_type),
                color = c("black", "red"), name = c("Hospitalised", "ICU")) |>
  hc_add_yAxis(nid = 1L, title = list(text = "Number of patients"), relative = 2) |> 
  hc_add_series(data = sgp_lineage, type = "column", hcaes(x = month, y = pct, group = line), 
                stacking = "normal", pointWidth = 15, yAxis = 1) |> 
  hc_add_yAxis(nid = 2L, title = list(text = "Submission Rate (%)"), relative = 1, 
               labels = list(format = "{value}%"), max = 100, opposite = TRUE) |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), 
           type = "datetime")
sgp_hosp_lineage
```

```{r export variant as jpeg from ggplot2 object}
jpeg("Singapore PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
sgp_lineage_plot
dev.off()
```

```{r export as jpeg for hchart object}
htmlwidgets::saveWidget(widget = sgp_hosp_lineage, file = "sgp_hosp_lineage.html")
getwd()
webshot(url = "sgp_hosp_lineage.html", 
        file = "sgp_hosp_lineage.jpeg",
        delay=3) # delay will ensure that the whole plot appears in the image
if(dev.cur() > 1) dev.off()
```

# Thailand
```{r variant}
tha_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Thailand") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, variant) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n))
ggplot(tha_variant, aes(month, pct, fill = variant)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom")
```
```{r lineage}
tha_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Thailand") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
tha_lineage_plot <- ggplot(tha_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ggtitle("Thailand") + ylab("Submission Rate (%)") +
  xlab(element_blank())
tha_lineage_plot
```
```{r export variant plot as jpeg}
jpeg("Thailand PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
tha_lineage_plot
dev.off()
```

# Vietnam
```{r variant}
vnm_variant <- data_gisaid_variant |> filter(date >= "2023-01-01", country == "Vietnam") |> 
  mutate(month = floor_date(as.Date(date), 'month'),
         line = gsub(".*\\((.*)\\).*", "\\1", variant)) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n)*100)
vnm_variant$line[vnm_variant$line == "B.1.1.529+BA.*"] <- "Omicron B.1.1.529+BA.*"
vnm_variant$line[vnm_variant$line == "XBB+XBB.* excluding XBB.1.5, XBB.1.16, XBB.1.9.1, XBB.1.9.2, XBB.2.3"] <- "XBB"
vnm_variant_plot <- ggplot(vnm_variant, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ggtitle("Vietnam") + ylab("Submission Rate (%)") +
  xlab(element_blank())
vnm_variant_plot
```
```{r lineage}
vnm_lineage <- data_gisaid_lineage |> filter(date >= "2023-01-01", country == "Vietnam") |> 
  mutate(month = floor_date(as.Date(date), 'month')) |> 
  arrange(date) |> 
  group_by(month, line) |> 
  summarise(n = sum(count)) |> 
  mutate(pct = n / sum(n))
ggplot(vnm_lineage, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  theme_prism() + theme(legend.position = "bottom")
```
```{r export variant as jpeg}
jpeg("Vietnam PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
vnm_variant_plot
dev.off()
```

# Export Plot
```{r}
jpeg("Thailand PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
tha_lineage_plot
dev.off()

jpeg("Vietnam PDR variant bar plot Dec23.jpeg", units="px", width=4000, height=2250, res=300)
vnm_variant_plot
dev.off()
```

```{r}
data <- data_owid |> 
  filter(date >= "2023-01-01", 
         iso_code %in% c("BRN", "KHM", "IDN", "LAO", "PHL", "THA", "VNM", "MMR", "SGP", "MYS"))
writexl::write_xlsx(data, "data_owid_asean.xlsx")
```

```{r export all variant into one image}
jpeg("all ams variant.jpeg", units = "px", width = 4250, height = 5500, res = 300)
ggarrange(brn_lineage_plot,
          khm_variant_plot,
          idn_lineage_plot,
          lao_variant_plot,
          mys_lineage_plot,
          mmr_variant_plot,
          phl_lineage_plot,
          sgp_lineage_plot,
          tha_lineage_plot,
          vnm_variant_plot, nrow = 5, ncol = 2, common.legend = TRUE, legend = "bottom")
dev.off()
```

```{r}
brn_lineage$country <- "Brunei DS"
khm_variant$country <- "Cambodia"
idn_lineage$country <- "Indonesia"
lao_variant$country <- "Lao PDR"
mys_lineage$country <- "Malaysia"
mmr_variant$country <- "Myanmar"
phl_lineage$country <- "Philippines"
sgp_lineage$country <- "Singapore"
tha_lineage$country <- "Thailand"
vnm_variant$country <- "Vietnam"
data_ams_variant <- rbind(brn_lineage,
                          khm_variant,
                          idn_lineage,
                          lao_variant,
                          mys_lineage,
                          mmr_variant,
                          phl_lineage,
                          sgp_lineage,
                          tha_lineage,
                          vnm_variant)
```

```{r}
ams_variant_plot <- ggplot(data_ams_variant, aes(month, pct, fill = line)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_prism() + theme(legend.position = "bottom") + ylab("Submission Rate (%)") +
  xlab(element_blank()) + facet_wrap(vars(country), nrow = 5, ncol = 2)
ams_variant_plot
```
```{r}
jpeg("all ams variant.jpeg", units = "px", width = 4000, height = 3000, res = 300)
ams_variant_plot
dev.off()
```


