---
title: "Asean_flunet_visualizations"
author: "himharis"
date: "2024-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(flextable)
library(zoo)
library(jsonlite)
library(httr)
library(highcharter)
```

```{r}
infUrl <- "https://developer.bluedot.global/casecounts/indicator-based/diseases/influenza/?locationIds=1880251,%201605651,%201694008,%201820814,%201733045,%201643084,%201831722,%201327865,%201655842,1562822&startDate=2023-01-01&api-version=v1"
res <- GET(infUrl, add_headers("Ocp-Apim-Subscription-Key" = "3f8e179c7c584514aa97faff3187df7d", "Cache-Control" = "no-cache")) |> content()
infData <- enframe(pluck(res, "data")) |> unnest_wider(value)
```

```{r weekly plot 2024 highcharter}
sorted_infData <- infData %>%
  arrange(reportedDate)

# Convert reportedDate to date format
sorted_infData$reportedDate <- as.Date(sorted_ibsData$reportedDate)

# Mutate positive rates
sorted_ibsData <- sorted_ibsData %>%
  mutate(positiveRates = (totalPositiveSamples / totalSpecimensReceived) * 100)

# Calculate mean values for each column
mean_totalPositiveSamplesA <- mean(sorted_ibsData$totalPositiveSamplesA, na.rm = TRUE)
mean_totalPositiveSamplesB <- mean(sorted_ibsData$totalPositiveSamplesB, na.rm = TRUE)
mean_positiveRates <- mean(sorted_ibsData$positiveRates, na.rm = TRUE)

# Fill missing values with mean
sorted_ibsData$totalPositiveSamplesA <- coalesce(sorted_ibsData$totalPositiveSamplesA, mean_totalPositiveSamplesA)
sorted_ibsData$totalPositiveSamplesB <- coalesce(sorted_ibsData$totalPositiveSamplesB, mean_totalPositiveSamplesB)
sorted_ibsData$positiveRates <- coalesce(sorted_ibsData$positiveRates, mean_positiveRates)
```

```{r}
# Slice sorted_ibsData to include only the required columns
plot_data <- sorted_ibsData %>%
  select(reportedDate, totalPositiveSamplesA, totalPositiveSamplesB, positiveRates)

plot <- highchart() |> 
  hc_add_series(data = plot_data, type = "column", hcaes(x = reportedDate, y = totalPositiveSamplesA), name = "No. of Influenza A", color = "cyan") |> 
  hc_add_series(data = plot_data, type = "column", hcaes(x = reportedDate, y = totalPositiveSamplesB), name = "No. of Influenza B", color = "blue")  |> 
  hc_xAxis(dateTimeLabelFormats = list(month = "%b '%y"), type = "datetime") |> 
  hc_plotOptions(column = list(marker = list(enabled = TRUE), pointWidth = 8))  # Adjust pointWidth as needed

plot
```
