---
title: "other diseases data collection"
output: html_document
date: "2023-07-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE, warning=FALSE}
library(httr)
library(jsonlite)
library(tidyverse)
library(flextable)
```

```{r setting date}
startDate <- "2023-12-24"
endDate <- "2023-12-30"
```

# Aggregate data from bluedot among AMS
```{r}
ams <- c(1880251, 1605651, 1694008, 1820814, 1733045, 1643084, 1831722, 1327865, 1655842,1562822)
ams_event_aggr <- data.frame()
for (i in ams){
  url <- paste0("https://developer.bluedot.global/casecounts/locations/", i, "?startDate=", startDate, "&endDate=", endDate, "&isAggregated=true&includeSources=false&api-version=v1")
  res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
  data <- enframe(pluck(res, "data")) |> unnest_wider(value)
  ams_event_aggr <- rbind(ams_event_aggr, data)
}
```


# Singapore
## Indicator-based Surveillance data from Bluedot
```{r cumulative}
sgpUrl <- "https://developer.bluedot.global/casecounts/indicator-based/?locationIds=1880251&startDate=2023-01-01&sourceOrgNames=Ministry%20of%20Health%20Singapore&api-version=v1"
res <- GET(sgpUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
sgpData <- enframe(pluck(res, "data")) |> unnest_wider(value) |> 
  select(diseaseName, totalReportedCases, totalConfirmedCases, totalDeaths) |>
  arrange(diseaseName) |> group_by(diseaseName) |> 
  summarise(cases = sum(totalReportedCases),
            deaths = sum(totalDeaths))
flextable(sgpData)
#View(sgpData)
```

```{r weekly}
sgpUrl <- "https://developer.bluedot.global/casecounts/indicator-based/?locationIds=1880251&startDate=2023-12-03&sourceOrgNames=Ministry%20of%20Health%20Singapore&api-version=v1"
res <- GET(sgpUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
sgpData <- enframe(pluck(res, "data")) |> unnest_wider(value) |> 
  select(reportingPeriodStartEpiWeek, diseaseName, 
         totalReportedCases, totalConfirmedCases, totalDeaths) |> arrange(diseaseName)
flextable(sgpData)
#View(sgpData)
```

# Other countries (China, ROK, Japan, Taiwan, Hong Kong, Macau, Timor Leste)
```{r}
country <- c(1814991, 1835841, 1861060, 1668284, 1819730, 1821275, 1966436)
other_event_aggr <- data.frame()
for (i in country){
  url <- paste0("https://developer.bluedot.global/casecounts/locations/", i, "?startDate=", startDate, "&endDate=", endDate, "&isAggregated=true&includeSources=false&api-version=v1")
  res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
  data <- enframe(pluck(res, "data")) |> unnest_wider(value)
  other_event_aggr <- rbind(other_event_aggr, data)
}
```

# Collect routine MMWR diseases from Bluedot
```{r}
disease <- c(55, 141, 10, 43, 4)
disease_aggr <- data.frame()
for (i in disease){
  url <- paste0("https://developer.bluedot.global/casecounts/diseases/", i, "?locationIds=1880251,1605651,1694008,1820814,1733045,1643084,1831722,1327865,1655842,1562822&startDate=2023-01-01&endDate=", endDate, "&isAggregated=true&api-version=v1")
  res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
  data <- enframe(pluck(res, "data")) |> unnest_wider(value)
  disease_aggr <- rbind(disease_aggr, data)
}
```

# Function to get data from Bluedot based on diseases among AMS
```{r}
bluedot_cases <- function(code, start_date, end_date){
  url <- paste0("https://developer.bluedot.global/casecounts/diseases/", code, "?locationIds=1880251,1605651,1694008,1820814,1733045,1643084,1831722,1327865,1655842,1562822&startDate=", start_date, "&endDate=", end_date, "&isAggregated=true&api-version=v1")
  res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
  data <- enframe(pluck(res, "data")) |> unnest_wider(value) |> 
    select(diseaseName, locationName, totalReportedCases, totalConfirmedCases, totalSuspectedCases, totalDeaths)
  return(data)
}
```

```{r}
data <- bluedot_cases(code = 64, start_date = "2023-01-01", end_date = "2024-01-09")
```

# Legionellosis

```{r}
legionellosisData <- bluedot_cases(code = 99, start_date = "2023-01-01", end_date = "2023-12-31")
```

# Nipah

```{r}
nipahData <- bluedot_cases(code = 41, start_date = "2023-01-01", end_date = "2023-12-31")
```

# Ethiopia

## News

```{r}
url <- "https://developer.bluedot.global/casecounts/locations/337996?startDate=2023-01-01&isAggregated=false&includeSources=true&api-version=v1"
res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
length_df <- length(res$data)
news <- data.frame()
for(i in 1:length_df){
  disease_name <- pluck(res, "data", i, "diseaseName")
  vec <- enframe(pluck(res, "data", i, "sources")) |> unnest_wider(value)
  vec$name <- disease_name
  news <- rbind(news, vec)
}
flextable(news)
```

## Aggregate

```{r}
url <- "https://developer.bluedot.global/casecounts/locations/337996?diseaseIds=&startDate=2023-01-01&isAggregated=true&includeSources=false&api-version=v1"
res <- GET(url, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
data <- enframe(pluck(res, "data")) |> unnest_wider(value) |> select(diseaseName, countryName, totalReportedCases, totalConfirmedCases, totalSuspectedCases, totalDeaths)
flextable(data)
```

# Zika

```{r}
zikaUrl <- paste0("https://developer.bluedot.global/casecounts/diseases/88?locationIds=1820814,%201831722,%201643084,%201655842,%201733045,%201327865,%201694008,%201880251,%201605651,%201562822,%201861060,%201835841,%201814991&startDate=2023-09-01&isAggregated=true&api-version=v1")
res <- GET(zikaUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
zikaData <- enframe(pluck(res, "data")) |> unnest_wider(value) |> select(diseaseName, countryName, totalReportedCases, totalConfirmedCases, totalSuspectedCases, totalDeaths)
flextable(zikaData)
```

# Chikungunya Cases

```{r}
chikungunyaUrl <- paste0("https://developer.bluedot.global/casecounts/diseases/53?locationIds=1820814,%201831722,%201643084,%201655842,%201733045,%201327865,%201694008,%201880251,%201605651,%201562822,%201861060,%201835841,%201814991&startDate=2023-01-01&endDate=", endDate, "&isAggregated=true&api-version=v1")
res <- GET(chikungunyaUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
chikungunyaData <- enframe(pluck(res, "data")) |> unnest_wider(value) |> select(diseaseName, countryName, totalReportedCases, totalConfirmedCases, totalSuspectedCases, totalDeaths)
flextable(chikungunyaData)
```

# Pertussis

```{r}
zikaUrl <- paste0("https://developer.bluedot.global/casecounts/diseases/13?locationIds=1820814,%201831722,%201643084,%201655842,%201733045,%201327865,%201694008,%201880251,%201605651,%201562822,%201861060,%201835841,%201814991&startDate=2023-11-01&isAggregated=true&api-version=v1")
res <- GET(zikaUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
zikaData <- enframe(pluck(res, "data")) |> unnest_wider(value) |> select(diseaseName, countryName, totalReportedCases, totalConfirmedCases, totalSuspectedCases, totalDeaths)
flextable(zikaData)
```

# TB

```{r}
zikaUrl <- paste0("https://developer.bluedot.global/casecounts/diseases/7?locationIds=1820814,%201831722,%201643084,%201655842,%201733045,%201327865,%201694008,%201880251,%201605651,%201562822,%201861060,%201835841,%201814991&startDate=2023-11-01&isAggregated=true&api-version=v1")
res <- GET(zikaUrl, add_headers("Ocp-Apim-Subscription-Key" = "5f645982e25d4a729d7292b890a8ed31", "Cache-Control" = "no-cache")) |> content()
zikaData <- enframe(pluck(res, "data")) |> unnest_wider(value) |> select(diseaseName, countryName, totalReportedCases, totalConfirmedCases, totalSuspectedCases, totalDeaths)
flextable(zikaData)
```
