---
title: "who_gho"
author: "Aldilas AN"
date: "2023-12-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(jsonlite)
library(tidyverse)
library(flextable)
library(lubridate)
library(writexl)
```

# Indicators

```{r}
indUrl <- "https://ghoapi.azureedge.net/api/Indicator?$filter=contains(IndicatorName,'HIV')"
res <- GET(indUrl) |> content()
indicator <- enframe(pluck(res, "value")) |> unnest_wider(value)
flextable(indicator)
```

# List of country

```{r}
countryUrl <- "https://ghoapi.azureedge.net/api/DIMENSION/COUNTRY/DimensionValues"
res <- GET(countryUrl) |> content()
country <- enframe(pluck(res, "value")) |> 
  unnest_wider(value) |> select(Code, Title) |> 
  rename(country_code = Code, country_name = Title)
```

# Prevalence of HIV among adults aged 15 to 49 (%)

```{r}
url <- "https://ghoapi.azureedge.net/api/MDG_0000000029"
res <- GET(url) |> content()
data <- enframe(pluck(res, "value")) |> unnest_wider(value) |> 
  filter(SpatialDim %in% c("BRN", "KHM", "IDN", "LAO", "PHL", "THA", "VNM", "MMR", "SGP", "MYS"),
         TimeDim >= 2010)
```

## Plot

```{r}
ggplot(data, aes(TimeDim, NumericValue)) + geom_line(aes(color = SpatialDim))
```

# Antiretroviral therapy coverage among people with HIV infection eligible for ART according to 2010 guidelines (%)
```{r}
url <- "https://ghoapi.azureedge.net/api/MDG_0000000033"
res <- GET(url) |> content()
data <- enframe(pluck(res, "value")) |> unnest_wider(value) |> 
  filter(SpatialDim %in% c("BRN", "KHM", "IDN", "LAO", "PHL", "THA", "VNM", "MMR", "SGP", "MYS"))
```

## Plot
```{r}
ggplot(data, aes(TimeDim, NumericValue)) + geom_line(aes(color = SpatialDim))
```

